# Generated by Django 4.1.6 on 2023-05-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categorymatcher',
            options={},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['-created'], name='api_categor_created_a76961_idx'),
        ),
        migrations.AddIndex(
            model_name='categorymatcher',
            index=models.Index(fields=['-created'], name='api_categor_created_fd2348_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-date', 'amount'], name='api_transac_date_38c3a4_idx'),
        ),
    ]
