### Importing mBank transaction file
POST http://127.0.0.1:8000/files/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"

< operations.csv
--WebAppBoundary--

### GET request with a header
GET http://127.0.0.1:8000/files/
Accept: application/json
