# Generated by Django 4.1.6 on 2023-03-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=512)),
                ('account', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLogMerge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('from_transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='merge_transaction_from_set', to='merger.transactionlog')),
                ('to_transaction', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='merge_transaction_to_set', to='merger.transactionlog')),
            ],
        ),
    ]
