# Generated by Django 4.1.6 on 2023-04-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0003_transactioncategory_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategorymatcher',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='category_matcher_set', to='merger.transactioncategory'),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transaction_log_set', to='merger.transactioncategory'),
        ),
    ]
