# Generated by Django 4.1.6 on 2023-05-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0004_transactioncategorymatcher_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlog',
            options={},
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transactioncategorymatcher',
            name='regex_expression',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionlogmerge',
            name='from_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='frommerge', to='merger.transactionlog'),
        ),
        migrations.AlterField(
            model_name='transactionlogmerge',
            name='to_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tomerge', to='merger.transactionlog'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['date', 'description', 'account', 'amount'], name='merger_tran_date_3c3d6d_idx'),
        ),
    ]
