# Generated by Django 4.1.6 on 2023-05-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0005_alter_transactionlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
